# Annotation: 
## Supplementary Table 2.Read raw counts. <br>
The following acronyms were used: <br>

## Controls:
V: Vialone Nano; B: Baldo; <br>
R: root; L: leaves; 

## 2 Experimental Conditions: 
T: treated (3 days salt-stressed seedlings); 
C: control (without salt stress); 
1,2,3 suffices stand for technical replicates.

In [16]:
import pandas as pd
import numpy as np
from math import *
from scipy.stats import ttest_ind

df = pd.read_csv('rna_data.csv', header=0, low_memory=False)
df['p_score'] = nan
#df

In [17]:
# Vialone Nano - Leaf 
df['VL_fold'] = np.log2(df[['VLT1','VLT2','VLT3']].mean(axis=1) / df[['VLC1','VLC2','VLC3']].mean(axis=1))

data_set1 = df[['VLT1','VLT2','VLT3']].to_numpy()
data_set2 = df[['VLC1','VLC2','VLC3']].to_numpy()

for i in range(len(df)):
    df.at[i,'p_score'] =  ttest_ind(data_set1[i], data_set2[i])[1] 

df = df[df['p_score'] < 0.01]
df

C:\Users\DHRUBO\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\arraylike.py:358: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)

,GenID,VLT1,VLT2,VLT3,VLC1,VLC2,VLC3,VRT1,VRT2,VRT3,...,BLC2,BLC3,BRT1,BRT2,BRT3,BRC1,BRC2,BRC3,p_score,VL_fold
24,Os01g03760,1736,1690,1614,1092,1004,916,3642,2812,2534,...,747,651,2753,3258,4514,2691,3858,3765,0.000402,0.742702
30,Os01g05510,530,472,533,400,377,344,727,632,558,...,142,115,190,285,358,269,391,201,0.005773,0.453452
34,Os01g08680,260,191,198,92,82,90,170,126,111,...,86,103,144,127,192,103,140,150,0.004403,1.297681
37,Os01g09280,927,701,769,464,462,413,699,551,392,...,436,480,419,424,702,199,247,269,0.006925,0.840074
41,Os01g10800,256,250,276,422,346,378,90,72,70,...,354,248,51,77,72,57,83,90,0.006573,-0.551367
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55751,Os12g43750,76,109,81,35,30,43,130,92,100,...,39,48,85,129,158,98,193,77,0.008571,1.300395
55760,Os12g43870,33,45,53,15,15,18,7,10,1,...,22,13,4,8,18,0,3,2,0.009368,1.448461
55765,Os12g43930,422,470,403,260,221,213,558,525,341,...,199,184,382,495,644,482,577,389,0.001249,0.899945
55782,Os12g44140,530,482,469,392,365,361,863,685,587,...,306,307,605,658,984,618,743,765,0.004462,0.405651
55796,Os12g44310,8822,8000,8771,10504,9879,10619,2318,1759,1528,...,7704,7107,1256,1648,1908,1532,1963,1485,0.006842,-0.276612

In [18]:
# Vialone Nano - Root 
df['VR_fold'] = np.log2(df[['VRT1','VRT2','VRT3']].mean(axis=1) / df[['VRC1','VRC2','VRC3']].mean(axis=1))

data_set1 = df[['VRT1','VRT2','VRT3']].to_numpy()
data_set2 = df[['VRC1','VRC2','VRC3']].to_numpy()

for i in range(len(df)):
    df.at[i,'p_score'] =  ttest_ind(data_set1[i], data_set2[i])[1] 

df = df[df['p_score'] < 0.01]
df

C:\Users\DHRUBO\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\arraylike.py:358: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)

,GenID,VLT1,VLT2,VLT3,VLC1,VLC2,VLC3,VRT1,VRT2,VRT3,...,BLC3,BRT1,BRT2,BRT3,BRC1,BRC2,BRC3,p_score,VL_fold,VR_fold
86,Os01g37910,5196.0,5229.0,5320.0,3269.0,2757.0,3001.0,6172.0,5263.0,4753.0,...,5543.0,4728.0,6598.0,6776.0,4998.0,5788.0,3490.0,0.006863,0.802575,0.492789
383,Os01g16540,1344.0,1375.0,1317.0,1095.0,926.0,1025.0,1684.0,1298.0,1102.0,...,692.0,1234.0,1487.0,1874.0,1186.0,1681.0,1598.0,0.004726,0.406010,0.482533
392,Os01g17214,515.0,663.0,636.0,974.0,950.0,1111.0,44.0,18.0,21.0,...,742.0,35.0,29.0,26.0,35.0,45.0,50.0,0.008812,-0.742522,-0.764512
509,Os01g26940,1061.0,989.0,1135.0,845.0,854.0,808.0,1490.0,1166.0,1088.0,...,753.0,1210.0,1456.0,1768.0,1219.0,1671.0,1535.0,0.008338,0.345331,0.330721
515,Os01g27210,1361.0,1267.0,940.0,390.0,397.0,403.0,1029.0,782.0,372.0,...,255.0,187.0,207.0,478.0,387.0,186.0,253.0,0.002665,1.584154,1.296057
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3918,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.005148,NaN,NaN
3939,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.007265,NaN,NaN
3947,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.007690,NaN,NaN
3969,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.002462,NaN,NaN
3982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000441,NaN,NaN

In [19]:
# Baldo - Leaf 
df['BL_fold'] = np.log2(df[['BLT1','BLT2','BLT3']].mean(axis=1) / df[['BLC1','BLC2','BLC3']].mean(axis=1))

data_set1 = df[['BLT1','BLT2','BLT3']].to_numpy()
data_set2 = df[['BLC1','BLC2','BLC3']].to_numpy()

for i in range(len(df)):
    df.at[i,'p_score'] =  ttest_ind(data_set1[i], data_set2[i])[1] 

df = df[df['p_score'] < 0.01]
df

C:\Users\DHRUBO\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\arraylike.py:358: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)
<ipython-input-19-074d3c2f43fa>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['BL_fold'] = np.log2(df[['BLT1','BLT2','BLT3']].mean(axis=1) / df[['BLC1','BLC2','BLC3']].mean(axis=1))
C:\Users\DHRUBO\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\frame.py:3281: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.loc[index, col] = value

,GenID,VLT1,VLT2,VLT3,VLC1,VLC2,VLC3,VRT1,VRT2,VRT3,...,BRT1,BRT2,BRT3,BRC1,BRC2,BRC3,p_score,VL_fold,VR_fold,BL_fold
637,Os01g37470,452.0,442.0,582.0,213.0,105.0,127.0,426.0,303.0,278.0,...,386.0,499.0,553.0,259.0,454.0,423.0,0.009872,1.729815,0.187945,1.069293
1069,Os01g66890,899.0,808.0,837.0,1375.0,1481.0,1848.0,408.0,344.0,226.0,...,386.0,525.0,758.0,718.0,853.0,500.0,0.002387,-0.886789,-0.052151,-0.743058
4027,Os01g41220,754.0,741.0,753.0,458.0,412.0,535.0,591.0,590.0,441.0,...,386.0,550.0,1111.0,683.0,715.0,572.0,0.001473,0.678072,-0.023818,0.596858
4029,Os01g41240,251.0,276.0,153.0,425.0,574.0,531.0,1009.0,1079.0,521.0,...,143.0,177.0,421.0,42.0,27.0,121.0,0.008153,-1.169925,2.063879,-0.809948
4058,Os01g41550,179.0,144.0,176.0,74.0,106.0,96.0,770.0,945.0,593.0,...,506.0,601.0,1835.0,512.0,581.0,735.0,0.007120,0.854372,0.382079,0.396890
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3642,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.002669,NaN,NaN,NaN
3658,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.008665,NaN,NaN,NaN
3663,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000044,NaN,NaN,NaN
3676,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.002455,NaN,NaN,NaN
3687,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.009148,NaN,NaN,NaN

In [20]:
# Baldo - Root 
df['BR_fold'] = np.log2(df[['BRT1','BRT2','BRT3']].mean(axis=1) / df[['BRC1','BRC2','BRC3']].mean(axis=1))

data_set1 = df[['BRT1','BRT2','BRT3']].to_numpy()
data_set2 = df[['BRC1','BRC2','BRC3']].to_numpy()

for i in range(len(df)):
    df.at[i,'p_score'] =  ttest_ind(data_set1[i], data_set2[i])[1] 

df = df[df['p_score'] < 0.01]
df

C:\Users\DHRUBO\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\arraylike.py:358: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)
<ipython-input-20-c4dc236cf1d6>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['BR_fold'] = np.log2(df[['BRT1','BRT2','BRT3']].mean(axis=1) / df[['BRC1','BRC2','BRC3']].mean(axis=1))
C:\Users\DHRUBO\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\frame.py:3281: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.loc[index, col] = value

,GenID,VLT1,VLT2,VLT3,VLC1,VLC2,VLC3,VRT1,VRT2,VRT3,...,BRT2,BRT3,BRC1,BRC2,BRC3,p_score,VL_fold,VR_fold,BL_fold,BR_fold
4027,Os01g41220,754.0,741.0,753.0,458.0,412.0,535.0,591.0,590.0,441.0,...,550.0,1111.0,683.0,715.0,572.0,0.001473,0.678072,-0.023818,0.596858,0.055315
4029,Os01g41240,251.0,276.0,153.0,425.0,574.0,531.0,1009.0,1079.0,521.0,...,177.0,421.0,42.0,27.0,121.0,0.008153,-1.169925,2.063879,-0.809948,1.963474
4058,Os01g41550,179.0,144.0,176.0,74.0,106.0,96.0,770.0,945.0,593.0,...,601.0,1835.0,512.0,581.0,735.0,0.007120,0.854372,0.382079,0.396890,0.686531
4075,Os01g41720,39.0,29.0,38.0,8.0,14.0,7.0,1.0,1.0,3.0,...,0.0,1.0,0.0,0.0,0.0,0.002652,1.869939,2.321928,1.703607,inf
4082,Os01g41820,285.0,380.0,338.0,163.0,107.0,143.0,4.0,11.0,2.0,...,6.0,11.0,1.0,7.0,1.0,0.003554,1.280108,1.280108,0.705071,1.353637
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3403,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.001159,NaN,NaN,NaN,NaN
3421,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN
3540,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.002462,NaN,NaN,NaN,NaN
3546,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.004856,NaN,NaN,NaN,NaN
3564,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.009338,NaN,NaN,NaN,NaN